cleanrl/ppg_procgen_fast.py
cleanrl/ppo_procgen_fast.py

Video length increased to 600 from prior value of 100 for ppo_procgen_fast.py and ppg_procgen_fast.py. Video length of 100 proved to be too short for truly assessing or watching the gameplay of some games in the Procgen benchmark. Additionally, pybullet import was removed from ppo_procgen_fast.py as it was an unnecessary import.

Video length increase for Procgen

---

README.md

Previously, the hyperlink went to https://github.com/vwxyzjn/cleanrl/blob/master/wandb.com

Fix hyperlink to actually go to Weights and Biases

---

poetry.lock
pyproject.toml

This PR adds support for MuJoCo environments such as `Hopper-v2`. Only works for Linux.
```bash
poetry install -E mujoco
poetry install -E pybullet
poetry run python cleanrl/ppo_continuous_action.py --gym-id Hopper-v2
poetry run python cleanrl/ppo_continuous_action.py --gym-id HalfCheetahBulletEnv-v0
```

Add MuJoCo environments support.

---

.github/workflows/tests.yaml

This PR modifies the github action workflows such that they only run tests given changes to the `cleanrl` directory.

Only run tests given changes to the `cleanrl` directory

---

Dockerfile
cleanrl_utils/submit_exp.py

Currently running the following commands
```bash
poetry run python -m cleanrl_utils.submit_exp \
--docker-tag vwxyzjn/cleanrl-new:latest \
--command "poetry run python cleanrl/ppo.py --gym-id CartPole-v1 --total-timesteps 100000 --track --capture-video" \
--build
docker run vwxyzjn/cleanrl-new:latest /bin/bash -c "poetry run python cleanrl/ppo.py --gym-id CartPole-v1 --total-timesteps 100000 --track --capture-video --seed 1"
```
results in the following error.
```
docker: Error response from daemon: manifest for vwxyzjn/cleanrl-new:latest not found: manifest unknown: manifest unknown.
```
This PR adds the `--load` flag, so buildx will import the docker image to the local registry.

Import built docker image to local registry

---

poetry.lock
pyproject.toml

`torch==1.10.0` is giving me some memory leak issues in gym-microrts... Hence rolling back to 1.7.1

Rollback back PyTorch version for better compatibility

---

.github/workflows/tests.yaml
.github/workflows/utils_test.yaml
tests/test_atari.py

The latest github action envs are giving weird issue: `AttributeError: module 'setuptools._distutils' has no attribute 'version'.` Hence we are downgrading setuptools.

Downgrade setuptools

---

cleanrl/apex_dqn_atari.py
cleanrl/c51.py
cleanrl/c51_atari.py
cleanrl/ddpg_continuous_action.py
cleanrl/dqn.py
cleanrl/dqn_atari.py
cleanrl/offline/offline_dqn_atari_visual.py
cleanrl/offline/offline_dqn_cql_atari_visual.py
cleanrl/sac_continuous_action.py
cleanrl/td3_continuous_action.py

Quick updates and tweaks in response to #102 
- TD3: removed what seemed like the DDPG agent's training loop
- SAC: refactored following TD3's format, with some minor changes. Running experiments to compare with previous version.
While we are at it, here a two potential code changes that could be incorporated, as I tried to do in the `sac_continuous.py`.
1. using qf1() instead, since it calls forward() by default. Saves a few key strokes, hopefully making it even easier to read.
2. using F.mse_loss() instead of loss_fn = nn.MSELoss(). Having `mse_loss` at the line and column where the loss computation is done could be more intuitive to read.
Let me know what you think about 1 and 2, so I can change the files here accordingly.
The refactor looks great for the continuous values DDPG / TD3 / …

Refactor value tweaks for TD3 and SAC

---

cleanrl/apex_dqn_atari.py
cleanrl/c51.py
cleanrl/c51_atari.py
cleanrl/ddpg_continuous_action.py
cleanrl/dqn.py
cleanrl/dqn_atari.py
cleanrl/offline/offline_dqn_atari_visual.py
cleanrl/offline/offline_dqn_cql_atari_visual.py
cleanrl/sac_continuous_action.py
cleanrl/td3_continuous_action.py
poetry.lock
pyproject.toml
tests/test_atari.py

Continue on #79. This PR refactors the value based methods. Specifically, we
1. Adopted the replay buffer from Stable-baselines 3. SB3's replay buffer is well-implemented and its behavior is intuitive. That is, we can imagine what happens when we do `buffer.sample()` compared to something like `agent.learn()`, which is much more abstract. To this end, I think it's worth to adopt SB3's replay buffer. In the future, when SB3 introduce prioritized replay buffer (https://github.com/hill-a/stable-baselines/issues/751), it will also make it easier for us to adopt.
2. General format refactoring.

Refactor value based methods

---

cleanrl/ppg_procgen.py
cleanrl/ppo_procgen.py

This PR refactors PPO and PPG. Specifically,
In PPO:
* Match the learning rate of `5e-4`: see the screenshot from the procgen paper.
* Add reward normalization per the screenshot from the procgen paper.
* Add layer initialization for output layers: while the IMPALA network itself uses the default layer initialization ([common/models.py#L28-L69](https://github.com/openai/baselines/blob/ea25b9e8b234e6ee1bca43083f8f3cf974143998/baselines/common/models.py#L28-L69)), the actor and critics head still uses the corresponding initialization.
* Change the distribution mode from `hard` to `easy` (save compute) and correspondingly change `total_timesteps` from 100M to 25M.
* Turn off learning rate annealing by default per the screenshot 
In PPG:
* Refactor according to the new format
* Rescale the …

Refactor PPG and PPO for procgen

---

.github/workflows/tests.yaml
cleanrl/ddpg_continuous_action.py
cleanrl/sac_continuous_action.py
cleanrl/td3_continuous_action.py
pyproject.toml
tests/test_mujoco.py

The current DDPG SAC TD3 files are not compatible with mujoco envs (see below), and this PR fixes it.
```
(cleanrl-ghSZGHE3-py3.9) ➜  cleanrl git:(fix-mujoco-compatibility) ✗ python -i ddpg_continuous_action.py --gym-id Hopper-v2 --learning-starts 100
/home/costa/.cache/pypoetry/virtualenvs/cleanrl-ghSZGHE3-py3.9/lib/python3.9/site-packages/gym/envs/registration.py:479: UserWarning: WARN: The environment Hopper-v2 is out of date. You should consider upgrading to version `v3` with the environment ID `Hopper-v3`.
logger.warn(
global_step=23, episode_reward=8.566108703613281
global_step=41, episode_reward=7.716689109802246
global_step=63, episode_reward=17.882747650146484
global_step=73, episode_reward=6.347293853759766
global_step=86, episode_reward=10.202958106994629
global_step=99, …
```

Fix replay buffer compatibility with mujoco envs

---

cleanrl/apex_dqn_atari.py
cleanrl/rnd_ppo.py
cleanrl/sac_continuous_action.py
tests/test_atari.py

- Added SPS logging to match other files in #126
- Added `apex_dqn_atari.py` to `test_atari.py`
- Removed the comment pertaining to (1) using F.mse_loss() and (2) using qf1() instead of qf1.forward()
- removed `.forward()` calls to match the other files in #126 
- Added to `test_atari.py`

Tweaks for PR 'add-sps-qvalues'

---

cleanrl/apex_dqn_atari.py
cleanrl/c51.py
cleanrl/c51_atari.py
cleanrl/ddpg_continuous_action.py
cleanrl/dqn.py
cleanrl/dqn_atari.py
cleanrl/offline/offline_dqn_atari_visual.py
cleanrl/offline/offline_dqn_cql_atari_visual.py
cleanrl/sac_continuous_action.py
cleanrl/td3_continuous_action.py
tests/test_atari.py

This PR adds SPS and q-values metrics for value methods. 
This PR also use `F.mse_loss()` instead of `loss_fn = nn.MSELoss()`
@dosssman do you think we should also use `using qf1() instead, which calls forward() by default`?

Add SPS and q-values metrics for value-based methods

---

cleanrl/c51.py
cleanrl/c51_atari.py
cleanrl/ddpg_continuous_action.py
cleanrl/dqn.py
cleanrl/dqn_atari.py
cleanrl/sac_continuous_action.py
cleanrl/td3_continuous_action.py

Closes #133. Here is a demo for the fix:
[![asciicast](https://asciinema.org/a/475401.svg)](https://asciinema.org/a/475401)

Make seed work again in value methods

---

docs/rl-algorithms/ddpg.md

This PR fixes a typo. Follows up from #137

Fix typo in DDPG docs

---

docs/rl-algorithms/ddpg.md

- Fixed a few typos and proposed some reformulations of a few sentences.
- Added a little bit more details regarding DDPG's Q loss.
- Regarding the _hard time reproducing ddpg on Mujoco-v1_, I was wondering how feasible it would be to run fujimoto's DDPG.py etc.. on free-mujoco
Other than that, great job on the pretty complete documentation for DDPG @vwxyzjn @yooceii , and sorry for being late to the party :bow: 
If you are adding new algorithms or your change could result in performance difference, you may need to (re-)run tracked experiments. See https://github.com/vwxyzjn/cleanrl/pull/137 as an example PR.

DDPG documnetation tweaks; added Q loss equations and light explanation

---

.pre-commit-config.yaml
LICENSE

This PR gives proper attribution in the LICENSE, similar to [how ray has done it](https://github.com/ray-project/ray/blob/master/LICENSE). I didn't quite understand this in earlier years but let's do it right this time :)

Amend license to give proper attribution

---

cleanrl/ppo_atari_envpool.py

This PR provides a minor fix for the default wandb project name for `ppo_atari_envpool.py`.

Fix the default wandb project name in `ppo_atari_envpool.py`

---

.pre-commit-config.yaml
cleanrl/c51.py
cleanrl/c51_atari.py
cleanrl/ddpg_continuous_action.py
cleanrl/dqn.py
cleanrl/dqn_atari.py
cleanrl/ppg_procgen.py
cleanrl/ppo.py
cleanrl/ppo_atari.py
cleanrl/ppo_atari_envpool.py
cleanrl/ppo_atari_lstm.py
cleanrl/ppo_continuous_action.py
cleanrl/ppo_memory_env_lstm.py
cleanrl/ppo_pettingzoo.py
cleanrl/ppo_procgen.py
cleanrl/rnd_ppo.py
cleanrl/sac_continuous_action.py
cleanrl/td3_continuous_action.py
cleanrl_utils/buffers.py
cleanrl_utils/docker_queue.py
cleanrl_utils/paper_plot.py
cleanrl_utils/plot.py
cleanrl_utils/plot_individual.py

This PR automatically upgrades the python syntax via [pyupgrade](https://github.com/asottile/pyupgrade)

Auto-upgrade syntax via `pyupgrade`

---

cleanrl/ppo_continuous_action.py

This PR sets the `total-timesteps` of `ppo_continuous_action.py` to be 1M, which matches the same timesteps budget in the original paper. We will defer the documentation of this change when we do the ppo benchmark soon (see #121)

Let `ppo_continuous_action.py`only run 1M steps

---

cleanrl/ppo.py

This PR changes the default `total-timesteps` in `ppo.py` from 25000 to 500000. With 25000 steps, `ppo.py` cannot perfectly solve CartPole-v1, whereas with 500k steps `ppo.py` can. Going to add documentation in #163. Merging this now.

Change `ppo.py`'s default timesteps

---

benchmark/ppo.sh
cleanrl_utils/benchmark.py
docs/get-started/benchmark-utility.md
mkdocs.yml

This PR introduces utilities that help us to run the benchmark experiments more smoothly.
Previously, we relied on a very simple mechanism for conducting benchmark experiments such as 
https://github.com/vwxyzjn/cleanrl/blob/443bb141afd26db41f14ede4a5f2026a62a16756/benchmark/sac/mujoco.sh#L3-L7
Such bash script usage is pretty straightforward but lacks flexibility and configurability. This PR introduce a command such as 
```bash
OMP_NUM_THREADS=1 python -m cleanrl_utils.benchmark \
--env-ids CartPole-v1 Acrobot-v1 MountainCar-v0 \
--command "poetry run python cleanrl/ppo.py --track --cuda False" \
--num-seeds 3 \
--workers 3
```
which will automatically run experiments with`workers=3` subprocesses. A full example can be seen here:
```
OMP_NUM_THREADS=1 python -m cleanrl_utils.benchmark \ …
```

Introduce benchmark utilities

---

cleanrl/c51.py
cleanrl/c51_atari.py
cleanrl/ddpg_continuous_action.py
cleanrl/dqn.py
cleanrl/dqn_atari.py
cleanrl/ppo.py
cleanrl/ppo_atari.py
cleanrl/ppo_atari_envpool.py
cleanrl/ppo_atari_lstm.py
cleanrl/ppo_continuous_action.py
cleanrl/ppo_pettingzoo.py
cleanrl/ppo_procgen.py
cleanrl/rnd_ppo.py
cleanrl/sac_continuous_action.py
cleanrl/td3_continuous_action.py
cleanrl_utils/add_header.py

This PR adds a header string pointing users to the documentation site.
Wrote a utility script to help do so by `poetry run python -m cleanrl_utils.add_header`, which generates:
```
```

Add docs header

---

docs/rl-algorithms/overview.md
docs/rl-algorithms/ppo.md
docs/rl-algorithms/sac.md
mkdocs.yml

This PR fixes a few links in the docs and disables the mkdocs `navigation.instant` setting, which is known to cause issues (see https://github.com/squidfunk/mkdocs-material/issues/3797#issuecomment-1107816067).

Documentation improvement - fix links and mkdocs

---

README.md
docs/index.md

Clarify CleanRL is a non-modular library

---

.github/pull_request_template.md
docs/rl-algorithms/ddpg.md

JAX + DDPG docs fix

---

.github/workflows/poetry-lock-export.yaml

Sometimes `poetry add` or `poetry lock` results in a significant amount of lock time
This PR adds a CI workflow to leverage the CI's fast network to speed up poetry lock. See https://github.com/john-sandall/poetry-speed-test on how this is done.

Leverage CI to speed up poetry lock

---

docs/rl-algorithms/ppo-isaacgymenvs.md

Fix PPO + Isaac Gym Benchmark Script

---

LICENSE

The https://github.com/AIcrowd/neurips2020-procgen-starter-kit/blob/142d09586d2272a17f44481a115c4bd817cf6a94/LICENSE#L190 did not include proper copyright notice, so this PR explicitly explains this.

Clarify LICENSE info

---

cleanrl/td3_continuous_action.py

Fixes the noise sampling for the TD3 exploration, as pointed out in #259 
If you are adding new algorithms or your change could result in performance difference, you may need to (re-)run tracked experiments. See https://github.com/vwxyzjn/cleanrl/pull/137 as an example PR.

Fix for noise sampling for the TD3 exploration

---

cleanrl/ddpg_continuous_action_jax.py
cleanrl/dqn_atari_jax.py
cleanrl/dqn_jax.py
cleanrl/td3_continuous_action_jax.py

This PR refactors the *_jax.py implementations as follows:
- removes unused parameters from argparse (`torch-deterministic` as jax is deterministic by default, `cuda` as GPU is activated by default if available)
- fix pybullet envs in td3_jax and ddpg_jax
Given this is a **non-performance-impacting refactor**, re-running the benchmark is not required.

chore: remove unused parameters in jax implementations

---

cleanrl/dqn.py
cleanrl/dqn_atari.py
cleanrl/dqn_atari_jax.py
cleanrl/dqn_jax.py

This PR fixes a confusing word choice in our DQN implementation. Previously we had
`logits = q_network.apply(q_state.params, obs)`
However, the word logits usually refer to "unnormalized probabilities" (see [What is the meaning of the word logits in TensorFlow?](https://stackoverflow.com/questions/41455101/what-is-the-meaning-of-the-word-logits-in-tensorflow)). A more correct word of choice here is `q_values = q_network.apply(q_state.params, obs)`.
Given this is a **non-performance-impacting** refactor, re-running the benchmark is not required.
CC @santiontanon

Refactor dqn word choice

---

cleanrl/ppo.py
cleanrl/ppo_atari.py
cleanrl/ppo_atari_envpool.py
cleanrl/ppo_atari_lstm.py
cleanrl/ppo_atari_multigpu.py
cleanrl/ppo_continuous_action.py
cleanrl/ppo_continuous_action_isaacgym/ppo_continuous_action_isaacgym.py
cleanrl/ppo_pettingzoo_ma_atari.py
cleanrl/ppo_procgen.py
cleanrl/ppo_rnd_envpool.py

Resolving issue #207 
Unnnecessary ppo code removed, numerical accuracy was ensured by team members through debugger. Additional runs showing performance without the extra code can be found at the following wandb link: https://wandb.ai/bragajj/ppo_advcalc

Remove the unnecessary regular advantage code in PPO

---

README.md
docs/index.md

https://github.com/tinkoff-ai/CORL seems to be a great offline RL library that shares a similar design philosophy with us. Since we are not really developing offline RL algorithms, we should give a friendly pointer to them, especially given that they have done the same for us:

Point offline RL users to tinkoff-ai/CORL

---

.github/workflows/tests.yaml
.github/workflows/utils_test.yaml

This PR addresses https://github.com/actions/runner-images/issues/6002. TLDR; the `ubuntu-18.04` is getting deprecated by GitHub action and we are replacing our CI image with `ubuntu-22.04`

Upload the ubuntu image for github action

---

cleanrl/ddpg_continuous_action.py
cleanrl/sac_continuous_action.py
cleanrl/td3_continuous_action.py

Here's an error I got when running this code on cuda:
```
>>> import torch
>>> torch.FloatTensor((1 - 0) / 2.0, device="cuda:0")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
RuntimeError: legacy constructor expects device type: cpu but device type: cuda was passed
```

Depreciate legacy constructor so that cuda can be used

---

benchmark/td3.sh
cleanrl_utils/benchmark.py

This PR aims to automatically add some version control tags to `benchmark.py`. It helps with #296 and #307 because the version control tags help us compare the performance of different codebase versions.

Auto wandb tag with `benchmark.py`

---

cleanrl/c51.py
cleanrl/c51_atari.py
cleanrl/dqn.py
cleanrl/dqn_atari.py
cleanrl/dqn_atari_jax.py
cleanrl/dqn_jax.py

Fix DQN target update frequency

---

docs/rl-algorithms/dqn.md

Fix target-network-frequency in DQN documentation

---

cleanrl/ppo_atari_envpool_xla_jax_scan.py

#334 actually introduced a major bug... It's totally my bad 🙈
```
storage = storage.replace(
advantages=advantages,
returns=storage.advantages + storage.values,
)
```
should have been the following because `storage.advantages` has zero values.
```
storage = storage.replace(
advantages=advantages,
returns=advantages + storage.values,
)
```

bug: incorrect logic in GAE calculation

---

cleanrl/c51.py
cleanrl/c51_atari.py
cleanrl/c51_atari_jax.py
cleanrl/c51_jax.py

Proper description of v_min and v_max in C51 parser 

---

.pre-commit-config.yaml

Fixes the failing pre-commit due to the Jimmy "Ba" name. Sorry for being lazy and not checking whether it actually works.

lowercase Jimmy ba ignore in pre-commit

---

cleanrl/dqn.py
cleanrl/dqn_atari.py
cleanrl/dqn_atari_jax.py
cleanrl/dqn_jax.py
docs/rl-algorithms/dqn.md

According to #346, the **Polyak update rate** (`tau`) has been included as an argument to `dqn.py` and `dqn_atari.py` implementations.
It will allow soft updates of the target network, as already done for `dqn_jax.py`.

Added Polyak update rate for soft DQN target network updates

---

docs/get-started/installation.md

docs: fix typo

---

.github/workflows/tests.yaml
.github/workflows/utils_test.yaml

Poetry 1.3 has led to a bug our CI fails, see https://github.com/python-poetry/poetry/issues/7171
https://github.com/python-poetry/poetry/pull/7169 fixed the issue, ~I suggest to bump poetry directly to 1.4 and get our CI healthy again.~

bump poetry to 1.3.1

---

docs/rl-algorithms/dqn.md

Documented implementation detail between `atari_dqn.py` and the 2015 DQN paper 

dqn_atari, MSE loss vs clipped loss explanation

---

cleanrl/sac_atari.py
cleanrl/sac_continuous_action.py
docs/rl-algorithms/sac.md

The lagrange multiplier in the entropy constraint (alpha, H(\pi) < H) needs to be positive for the relaxation to work. This means that alpha not log alpha should be used here. See the Softlearnign code at:
https://github.com/rail-berkeley/softlearning/blob/13cf187cc93d90f7c217ea2845067491c3c65464/softlearning/algorithms/sac.py#L256
but the real question is:
A) does this matter?
B) am i making sense?
I'll answer A tomorrow, not sure about B tho.

use alpha not log alpha in autotune

---

cleanrl/sac_continuous_action.py

Address issues pointed out in #379 

Fixes actor_loss shape for SAC continuous

---

cleanrl/c51.py
cleanrl/c51_atari.py
cleanrl/c51_atari_jax.py
cleanrl/c51_jax.py
cleanrl/ddpg_continuous_action.py
cleanrl/ddpg_continuous_action_jax.py
cleanrl/dqn.py
cleanrl/dqn_atari.py
cleanrl/dqn_atari_jax.py
cleanrl/dqn_jax.py
cleanrl/ppo.py
cleanrl/ppo_continuous_action.py
cleanrl/qdagger_dqn_atari_impalacnn.py
cleanrl/rpo_continuous_action.py
cleanrl/sac_atari.py
cleanrl/sac_continuous_action.py
cleanrl/td3_continuous_action.py
cleanrl/td3_continuous_action_jax.py

This PR focuses on cleaning unused code, fixing annotations and reduces line differences between files.
Changes include:
- Removed unused codes in various files. (`video_filenames = set()`)
- Fixed annotations in various files. ("... handle `terminal_observation`" -> "... handle `final_observation`")
- Organized code to minimize line differences and enhance readability.
- Unified the make_env function
- next_obs, rewards, terminations, truncations, infos

Reducing Code Redundancy and Minimize Line Diffs

---

cleanrl/ppo_atari.py
cleanrl/ppo_atari_lstm.py
cleanrl/ppo_atari_multigpu.py

The current code is that the first wrapper saves the video and the second wrapper overwrites it with the same name.
In the `_atari_.py` algorithm, the RecordVideo code was duplicated and has been removed.

Remove duplicate code

---

cleanrl/sac_continuous_action.py

Removing the unused `noise_clip` from `sac_continuous_actions.py` (probably a relic from TD3)

Removing the unused noise_clip from sac_continuous_actions.py

---

README.md

This PR adds LeanRL as a related project https://github.com/pytorch-labs/LeanRL

Add LeanRL as a related project
