- cleanrl/experiments/impl_matters/ppo_continuous.py
- cleanrl/ppo2_continuous_actions.py
- Changed observations back to obs
- When bootstrapping, there was a missing `returns=returns[:-1]` which was borking the script.
- Some cleanups
> Fixed the incorrect dimensions of the return array when bootstrapping.

- cleanrl/ppo2_continuous_action.py
Glad if I could have your input on the entropy computation and how it is added to the policy loss.
Sorry for the # DEBUG lines, but I have to run right now.
> Added layer norm to policy network and entropy bonus to policy loss.

- cleanrl/ppo2_continuous_action.py
This is related to #12 .
Relevant code can be found in https://github.com/openai/baselines/blob/ea25b9e8b234e6ee1bca43083f8f3cf974143998/baselines/ppo2/model.py#L69
> PPO2 # fix value clipping

- cleanrl/rnd_ppo.py
Add the random network distillation implementation.
I've attached the episode_reward below.
> Add RND implementation

- cleanrl/dqn_atari.py
- cleanrl/dqn_atari_visual.py
- cleanrl/experiments/dqn2_atari_visual.py
where PrioritizedReplayBuffer is not used, unify the implementation of the ReplayBuffer, closes #35
> unify replay buffer

- cleanrl/ppg_procgen_fast.py
> Fast ppg_procgen implementation

- README.md
#53 
Remove links to algorithms which were removed, but still mentioned on readme.
> Remove links to deleted code on README algorithms

- cleanrl_utils/submit_exp.py
This PR removes the dummy cache.
> Remove docker dummy cache

- cleanrl_utils/submit_exp.py
This PR does not change the user API in https://docs.cleanrl.dev/cloud/submit-experiments/. This PR only has implementation improvement under the hood.
> Allow buildx to save to local and push

- cleanrl_utils/submit_exp.py
- poetry.lock
- pyproject.toml
This PR adds a `--aws-num-retries` argument to auto-restart the script. I haven't updated the documentation but it should help auto-resume the training process with instructions [here](https://docs.cleanrl.dev/advanced/resume-training/)
This PR also refactors the AWS Batch submission's job name to use docker tags instead.
> Cloud utilities refactor

- README.md
- docs/index.md
This PR updates the BibTeX entry for CleanRL (https://arxiv.org/abs/2111.08819).
> Update paper citation entry

- .gitpod.Dockerfile
- .gitpod.yml
This PR adds gitpod support. Gitpod is a cloud IDE that prepares the development environment with one click.
Here is a screenshot of what it looks like.
Try it out here.
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/vwxyzjn/cleanrl/tree/gitpod)
> Add Gitpod support

- README.md
- docs/index.md
This PR adds the isort and black badges. Pretty straightforward stuff.
> Add the isort and black badges

- .github/workflows/tests.yaml
- .github/workflows/utils_test.yaml
- poetry.lock
- pyproject.toml
> Update gym to 0.23.0

- poetry.lock
> Update to `gym==0.23.1`

- docs/rl-algorithms/ddpg.md
This PR corrects the DDPG description in the documentation.
> Fix DDPG docs' description

- docs/rl-algorithms/ddpg.md
> Fix incorrect links in the DDPG docs

- LICENSE
Add LICENSE information regarding SAC.
> Added License info regarding SAC

- cleanrl/ppo_procgen.py
This PR enable video recording for `ppo_procgen.py` via `--capture-video`
> Enable video recording for `ppo_procgen.py`

- README.md
- docs/get-started/examples.md
- docs/index.md
- docs/rl-algorithms.md
- docs/rl-algorithms/overview.md
This PR removes stale documentation on Apex-DQN and fixes the license badge being weird after #152 #153.
> Address stale documentation

- README.md
- cleanrl/ppo_pettingzoo_ma_atari.py
- docs/rl-algorithms/overview.md
- docs/rl-algorithms/ppo.md
> Fix documentation links in README.md

- docs/rl-algorithms/ppo.md
This PR fixes some documentation links.
> Fix the implemented varaints section in PPO

- pyproject.toml
This PR makes the first 1.0.0 beta release, bumping the version in pyproject.toml
> 1.0.0 Beta Release

- cleanrl/ppo_pettingzoo_ma_atari.py
> Fix documentation link

- .github/workflows/poetry-lock-export-ubuntu.yaml
> Ubuntu runner for poetry lock

- cleanrl/ppo_atari_envpool.py
Seed envpool environment, otherwise all envs are seeded with constant value (42)
> Seed envpool environment explicitly

- README.md
> Fix docs links in README.md

- README.md
- docs/index.md
This PR adds a note on the ongoing Gymnasium support, linking #263.
> Add a note on Gymnasium

- cleanrl/ppo_atari_envpool_xla_jax_scan.py
- tests/test_jax_compute_gae.py
This PR does a simple refactoring on the dataclass syntax in `ppo_atari_envpool_xla_jax_scan.py`.
> chore: simplify syntax

- README.md
> update paper link to point to JMLR version

- .github/workflows/tests.yaml
- tests/test_jax_compute_gae.py
Fix https://github.com/vwxyzjn/cleanrl/pull/337#pullrequestreview-1233392114
> Add test cases

- docs/rl-algorithms/ddpg.md
- docs/rl-algorithms/td3.md
Fix documentation of TD3 and DDPG to include JAX versions in `Implemented Variants`
> docs fix for ddpg and td3 to include jax implementation

- cleanrl/dqn.py
- cleanrl/dqn_atari.py
- cleanrl/dqn_atari_jax.py
- cleanrl/dqn_jax.py
Not sure why #347 did not trigger the CI.
> fix pre-commit

- .github/workflows/pre-commit.yml
- .github/workflows/tests.yaml
- .github/workflows/utils_test.yaml
> Allow CI to be triggered by third-party

- cleanrl/td3_continuous_action.py
- cleanrl/td3_continuous_action_jax.py
- cleanrl_utils/evals/td3_eval.py
- cleanrl_utils/evals/td3_jax_eval.py
- docs/get-started/zoo.md
- tests/test_mujoco_gymnasium.py
- tests/test_mujoco_py_gymnasium.py
> td3 huggingface integration

- cleanrl/ppo_continuous_action.py
- cleanrl_utils/evals/ppo_eval.py
> ppo_continuous_action huggingface integration

- cleanrl/ppo_atari.py
> fix video uploading 

- README.md
> [Docs] Fix in README.md

- README.md
- docs/rl-algorithms/ppo-trxl.md
Fixed typos in two links: one in README.md and one in ppo-trxl.md.
> fix ppo-trxl links

- docs/get-started/basic-usage.md
> Typo fix in basic-usage.md

- README.md
- docs/get-started/zoo.md
- docs/index.md
Change the word `varaint` to `variant`.
> varaint -> variant
